// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1gVEXa5nBd60KA6KlssYRTb9PF91QmCA',
    appId: '1:175061425970:web:4496362b5bb6049182012b',
    messagingSenderId: '175061425970',
    projectId: 'app-iot-7256c',
    authDomain: 'app-iot-7256c.firebaseapp.com',
    storageBucket: 'app-iot-7256c.appspot.com',
    measurementId: 'G-S2YVPDFWL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgs1hZR2i3xZR7q7lUgoODhK5P3u2UV5M',
    appId: '1:175061425970:android:c9be9debbc9a2d8282012b',
    messagingSenderId: '175061425970',
    projectId: 'app-iot-7256c',
    storageBucket: 'app-iot-7256c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlk4uZuC5kyrmCuXm6tlhP8Iz7AZjGdU',
    appId: '1:175061425970:ios:2f5499ca90d432f882012b',
    messagingSenderId: '175061425970',
    projectId: 'app-iot-7256c',
    storageBucket: 'app-iot-7256c.appspot.com',
    iosClientId: '175061425970-918l90hjtviodh40chacdlq8kl1ik86b.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoApp',
  );
}
